stages:
  - setup
  - test
  - lint

variables:
  FLUTTER_VERSION: "3.x"
  NODE_VERSION: "23"

cache:
  paths:
    - mobile/.pub-cache/
    - mobile/.dart_tool/
    - backend/node_modules/

# Setup Flutter
setup:flutter:
  stage: setup
  image: 
    name: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
    entrypoint: [""]
  script:
    - cd mobile
    - flutter pub get
  artifacts:
    paths:
      - mobile/pubspec.lock
    expire_in: 1 hour

# Setup Node.js
setup:node:
  stage: setup
  image: node:23
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1 hour

# Tests du backend
test:backend:
  stage: test
  image: node:23
  needs:
    - setup:node
  script:
    - cd backend
    - node app/scripts/initDB.js
    - npm run test

# Tests de l'application Flutter
test:flutter:
  stage: test
  image:
    name: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
    entrypoint: [""]
  needs:
    - setup:flutter
  script:
    - cd mobile
    - flutter test

# Lint Backend
lint:backend:
  stage: lint
  image: node:23
  needs:
    - setup:node
  script:
    - cd backend
    - npm run lint || true

# Lint Flutter
lint:flutter:
  stage: lint
  image:
    name: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
    entrypoint: [""]
  needs:
    - setup:flutter
  script:
    - cd mobile
    - flutter analyze