version: 2.1

orbs:
  node: circleci/node@5.1.0
  flutter: circleci/flutter@2.0.2

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16.0
  flutter-executor:
    docker:
      - image: cimg/android:2023.06-browsers

jobs:
  setup-backend:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ./backend
      - persist_to_workspace:
          root: .
          paths:
            - backend/node_modules
    
  test-backend:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Initialize Database
          command: cd backend && node app/scripts/initDB.js
      - run:
          name: Run Backend Tests
          command: cd backend && npm test
  
  setup-frontend:
    executor: flutter-executor
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.19.3
      - run:
          name: Flutter Version
          command: flutter --version
      - run:
          name: Get Flutter Dependencies
          command: cd mobile && flutter pub get
      - persist_to_workspace:
          root: .
          paths:
            - mobile/.pub-cache
            - mobile/.dart_tool
            - mobile/.flutter-plugins
            - mobile/.flutter-plugins-dependencies
  
  test-frontend:
    executor: flutter-executor
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.19.3
      - attach_workspace:
          at: .
      - run:
          name: Run Flutter Tests
          command: cd mobile && flutter test
  
  analyze-frontend:
    executor: flutter-executor
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.19.3
      - attach_workspace:
          at: .
      - run:
          name: Analyze Flutter Code
          command: cd mobile && flutter analyze

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup-backend
      - test-backend:
          requires:
            - setup-backend
      - setup-frontend
      - test-frontend:
          requires:
            - setup-frontend
      - analyze-frontend:
          requires:
            - setup-frontend