version: 2.1

executors:
  flutter:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.29.3
    environment:
      FLUTTER_VERSION: "3.29.3"
  node:
    docker:
      - image: node:23
    environment:
      NODE_VERSION: "23"

jobs:
  setup_flutter:
    executor: flutter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-flutter-{{ checksum "mobile/pubspec.lock" }}
      - run:
          name: Flutter pub get
          command: |
            cd mobile
            flutter pub get
      - save_cache:
          key: v1-flutter-{{ checksum "mobile/pubspec.lock" }}
          paths:
            - mobile/.pub-cache/
            - mobile/.dart_tool/
      - persist_to_workspace:
          root: .
          paths:
            - mobile/pubspec.lock

  setup_node:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ checksum "backend/package-lock.json" }}
      - run:
          name: NPM install
          command: |
            cd backend
            npm install
      - save_cache:
          key: v1-node-{{ checksum "backend/package-lock.json" }}
          paths:
            - backend/node_modules/
      - persist_to_workspace:
          root: .
          paths:
            - backend/node_modules/

  test_backend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Init DB
          command: |
            cd backend
            node app/scripts/initDB.js
      - run:
          name: Run backend tests
          command: |
            cd backend
            npm run test

  test_flutter:
    executor: flutter
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Flutter test
          command: |
            cd mobile
            flutter test

  lint_backend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint backend
          command: |
            cd backend
            npm run lint || true

  lint_flutter:
    executor: flutter
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Flutter analyze
          command: |
            cd mobile
            flutter analyze

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_flutter
      - setup_node
      - test_backend:
          requires:
            - setup_node
      - test_flutter:
          requires:
            - setup_flutter
      - lint_backend:
          requires:
            - setup_node
      - lint_flutter:
          requires:
            - setup_flutter