name: CI/CD Flutter & Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Jobs de setup
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: cd api/mobile && flutter pub get
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}

  setup-node:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm install

  # Jobs de test
  test-backend:
    name: Test Backend
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm install
      - run: cd api/backend && node app/scripts/initDB.js
      - run: cd api/backend && npm run test

  test-flutter:
    name: Test Flutter
    needs: setup-flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter test

  # Jobs de lint
  lint-backend:
    name: Lint Backend
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm install
      - run: cd api/backend && npm run format
      - run: cd api/backend && npm run lint || true

  lint-flutter:
    name: Lint Flutter
    needs: setup-flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter analyze

  # Jobs de build
  build-backend:
    name: Build Backend
    needs: [test-backend, lint-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - run: cd api/backend && npm ci --production
      - uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: api/backend/

  build-android:
    name: Build Android App
    needs: [test-flutter, lint-flutter]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: android-app-release
          path: api/mobile/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS App
    needs: [test-flutter, lint-flutter]
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ios-app-release
          path: api/mobile/build/ios/iphoneos
